services:
  cassandra:
    image: cassandra:5.0
    container_name: fitness-cassandra
    ports:
      - "9042:9042"          
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=FitnessCluster
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  cassandra_data: